services:
  # 1. Frontend (The Website UI)
  frontend:
    build: ./setup/frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - sims-net

  # 2. API (The Backend Logic)
  api:
    build: ./setup/api
    ports:
      - "5000:80"
    environment:
      - SQL_CONNECTION_STRING=Server=sql-db;Database=SIMS;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017/sims
    depends_on:
      - sql-db
      - mongo-db
    restart: unless-stopped
    networks:
      - sims-net

  # 3. SQL Database (for Incidents, Users) - Windows optimized
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - sims-net

  # SQL Database initializer
  sql-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sql-db
    volumes:
      - ./setup/mssql-init/setup.sql:/tmp/setup.sql:ro
    networks:
      - sims-net
    command: |
      /bin/bash -c '
      echo "Waiting for SQL Server to be ready..."
      sleep 30
      echo "Checking SQL Server connection..."
      until /opt/mssql-tools/bin/sqlcmd -S sql-db -U sa -P "${SQL_PASSWORD}" -l 30 -Q "SELECT 1" >/dev/null 2>&1; do
        echo "SQL Server not ready, waiting..."
        sleep 5
      done
      echo "SQL Server is ready, running setup script..."
      /opt/mssql-tools/bin/sqlcmd -S sql-db -U sa -P "${SQL_PASSWORD}" -d master -i /tmp/setup.sql
      echo "Setup complete!"
      '

  # 4. MongoDB (for Comments, Pictures)
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
      - ./setup/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - sims-net

  # 5. Grafana (for Data Visualization) - Windows optimized
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - sims-net

  # 6. Portainer (for Docker Container Management)
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    restart: unless-stopped
    networks:
      - sims-net

# Define a shared network for all containers
networks:
  sims-net:
    driver: bridge

# Define volumes
volumes:
  sql_data: