services:
  # 1. Frontend (The Website UI)
  frontend:
    build: ./setup/frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - sims-net

  # 2. API (With corrected build context)
  api:
    build: ./setup/api
    ports:
      # Maps port 5321 on your computer to port 5321 inside the container.
      - "5321:5321"
    environment:
      # This new line tells the .NET application to listen on port 5321 inside the container.
      - ASPNETCORE_URLS=http://+:5321
      # Added 'Encrypt=False' to the connection string to resolve connection issues.
      - SQL_CONNECTION_STRING=Server=sql-db;Database=SIMS;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;Encrypt=False
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017/sims
    depends_on:
      sql-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sims-net

  # 3. SQL Database (for Incidents, Users) - Windows optimized
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_CPU_COUNT=1
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - sims-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${SA_PASSWORD}\" -C -Q 'SELECT 1' || exit 1"]
      interval: 15s
      retries: 10
      timeout: 10s
      start_period: 60s

  # SQL Database initializer
  sql-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      sql-db:
        condition: service_healthy
    volumes:
      - ./setup/mssql-init/setup.sql:/tmp/setup.sql:ro
    networks:
      - sims-net
    command: |
      /bin/bash -c '
      echo "SQL Server is ready via healthcheck, running setup script..."
      /opt/mssql-tools/bin/sqlcmd -S sql-db -U sa -P "${SQL_PASSWORD}" -d master -i /tmp/setup.sql
      echo "Setup complete!"
      '

  # 4. MongoDB (for Comments, Pictures)
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
      - ./setup/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - sims-net
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' -u \"$${MONGO_USER}\" -p \"$${MONGO_PASSWORD}\" --quiet || exit 1"]
      interval: 15s
      retries: 10
      timeout: 10s
      start_period: 30s

  # 5. Grafana (for Data Visualization) - Windows optimized  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - SA_PASSWORD=${SQL_PASSWORD} # Passes the password to the datasource config
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      # Persistent storage for Grafana's internal database
      - ./data/grafana:/var/lib/grafana
      # Mount the provisioning files for datasources and dashboards
      - ./setup/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./setup/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Mount the actual dashboard JSON file
      - ./setup/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - sims-net

  # 6. Portainer (for Docker Container Management)
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    restart: unless-stopped
    networks:
      - sims-net

# Define a shared network for all containers
networks:
  sims-net:
    driver: bridge

# Define volumes
volumes:
  sql_data: