services:
  # 1. NGINX Reverse Proxy (The ONLY public entry point for all services)
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
      - grafana
      - portainer
    networks:
      - sims-net

  # 2. Frontend (The Website UI) - No longer exposed directly
  frontend:
    build: ./frontend
    networks:
      - sims-net

  # 3. API (The Backend Logic) - No longer exposed directly
  api:
    build: ./api
    environment:
      - SQL_CONNECTION_STRING=Server=sql-db;Database=SIMS;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017/
    depends_on:
      - sql-db
      - mongo-db
    networks:
      - sims-net

  # 4. SQL Database (for Incidents, Users)
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./data/sql:/var/opt/mssql
    networks:
      - sims-net

  # 5. MongoDB (for Comments, Pictures)
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    networks:
      - sims-net

  # 6. Grafana (for Data Visualization) - No longer exposed directly
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - sims-net

  # 7. Portainer (for Docker Container Management) - No longer exposed directly
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      # Mounts the Docker socket to allow Portainer to manage containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - sims-net

# Define a shared network for all containers
networks:
  sims-net:
    driver: bridge


