services:
  # 1. Frontend (The Website UI) - Now exposed on port 8080
  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Access via http://localhost:8080
    networks:
      - sims-net

  # 2. API (The Backend Logic) - Now exposed on port 5000
  api:
    build: ./api
    ports:
      - "5000:80" # The API is now available at http://localhost:5000
    environment:
      - SQL_CONNECTION_STRING=Server=sql-db;Database=SIMS;User ID=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-db:27017/
    depends_on:
      - sql-db
      - mongo-db
    networks:
      - sims-net

  # 3. SQL Database (for Incidents, Users) - Remains internal
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "${UID}:${GID}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./data/sql:/var/opt/mssql
    networks:
      - sims-net
    ports:
      - "1433:1433"

  # 4. MongoDB (for Comments, Pictures) - Remains internal
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    networks:
      - sims-net
    ports:
      - "27017:27017"

  # 5. Grafana (for Data Visualization) - Now exposed on port 3000
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Access via http://localhost:3000
    user: "${UID}:${GID}"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - sims-net

  # 6. Portainer (for Docker Container Management) - Now exposed on port 9443
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443" # Access via https://localhost:9443
    volumes:
      # Mounts the Docker socket to allow Portainer to manage containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - sims-net

# Define a shared network for all containers
networks:
  sims-net:
    driver: bridge
